### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by stcroppe** [thekalinga/bootstrap4-vscode#10]
Is it possible to provide Vue Template support for this vac extension?

**Comment by thekalinga** [comment]
I have published a newer version of plugin. Please verify

**Comment by shilik** [comment]
I tried, it doesn't work for .vue file.

**Comment by FetzenRndy** [comment]
Vue template Support is added in my PR just needs to be merged... Also this plugin isnt of any use atm since it only Supports the bootstrap 4 alpha and is not compatible with the beta...

**Comment by FetzenRndy** [comment]
Vue template Support is added in my PR just needs to be merged... Also this plugin isnt of any use atm since it only Supports the bootstrap 4 alpha and is not compatible with the beta...

**Comment by timster** [comment]
This doesn't seem to work for me.

Completions work outside the template block, but not in it. I think the problem is that the extension is registered to work with `vue` filetype and not `vue-html`.

I manually updated my install of the extension to get it working.

Added the following in the `snippets` section.

    {
      "language": "vue-html",
      "path": "./snippets.json"
    }

**Comment by resting** [comment]
@timster where do I find this `snippets` section?

**Comment by thekalinga** [comment]
Fixed in version 5.0.0. Please check & let me know if there are any issues
